import './globals.css'

interface Props {
  children: React.ReactNode
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

const AppLayout = (props: Props) => {
  const { children } = props

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

export default AppLayout
